### PR TITLE
Build Docker image for ARM

### PR DESCRIPTION
**Pull request by ben-z**
This allows us to run this image in our new multi-arch Azure Kubernetes cluster.

Similar to https://github.com/WATonomous/slurm-dist/pull/2 and https://github.com/WATonomous/repo-ingestion/pull/1/files

cc @Jimmyj30

### CODE REVIEW

**Comment by ben-z** [comment]
@Jimmyj30 can you help me run prettier on this and deploy it? https://github.com/WATonomous/infra-config/pull/2972

**Comment by Jimmyj30** [comment]
> @Jimmyj30 can you help me run prettier on this and deploy it? [WATonomous/infra-config#2972](https://github.com/WATonomous/infra-config/pull/2972)

Okies, sg

I think this should get deployed on the next run of CI right?

**Comment by ben-z** [comment]
> I think this should get deployed on the next run of CI right?

We'll want to update the pinned version:
https://github.com/WATonomous/infra-config/blob/6890dba8fd87f38a9d9afd99f89638e0c87638f0/common/kubernetes_images.yml#L9-L10

**Review by Jimmyj30 — APPROVED** [review]

**Comment by Jimmyj30** [comment]
@ben-z 
just curious, the updated image can be "magically" run on both the amd64 and arm64 platforms right?

**Comment by ben-z** [comment]
> @ben-z just curious, the updated image can be "magically" run on both the amd64 and arm64 platforms right?

Yea there will be a root manifest that reference both ARM and AMD images. When we pin versions, if we use the checksum of the root manifest instead of the individual image manifests, then the image runner will automatically choose based on the platform.

**Comment by ben-z** [comment]
And the root manifest checksum is the one shown on this page I'm pretty sure: 
image

**Pull request merged**
